#include "src/main.c"
#include "src/debugfont.c"
#include "src/diamondsquare.c"
#include "src/tga.c"
#include "src/tgaasset.c"

#include "../../src/asset.c"
#include "../../src/assetcache.c"
#include "../../src/assetdir.c"
#include "../../src/assetmap.c"
#include "../../src/assetstorage.c"

#include "../../../taasdk/src/conditionvar.c"
#include "../../../taasdk/src/keyboard.c"
#include "../../../taasdk/src/log.c"
#include "../../../taasdk/src/mouse.c"
#include "../../../taasdk/src/mutex.c"
#include "../../../taasdk/src/path.c"
#include "../../../taasdk/src/gl.c"
#include "../../../taasdk/src/glcontext.c"
#include "../../../taasdk/src/semaphore.c"
#include "../../../taasdk/src/system.c"
#include "../../../taasdk/src/thread.c"
#include "../../../taasdk/src/timer.c"
#include "../../../taasdk/src/window.c"
#include "../../../taasdk/src/workqueue.c"
